//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""e1d6bcae-ee3c-47b1-8e72-5dd1a34fb494"",
            ""actions"": [
                {
                    ""name"": ""EnableLeftRayInteractor"",
                    ""type"": ""Button"",
                    ""id"": ""4be6cdb4-2b8b-4a09-9ff5-5e6411a56d8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableRightRayInteractor"",
                    ""type"": ""Button"",
                    ""id"": ""d2f8bb75-7edc-4ecc-a3f7-0626dc43f5c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bab18374-b113-4e30-9e6a-daed56fdadf3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableLeftRayInteractor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9012c2b1-6d65-46b5-9129-10c5c2375381"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableLeftRayInteractor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f0f334e-9f1d-4738-9018-c09bd9981083"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableRightRayInteractor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2878baa4-7a27-4afa-9717-c92f440c893a"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableRightRayInteractor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_EnableLeftRayInteractor = m_Player.FindAction("EnableLeftRayInteractor", throwIfNotFound: true);
        m_Player_EnableRightRayInteractor = m_Player.FindAction("EnableRightRayInteractor", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_EnableLeftRayInteractor;
    private readonly InputAction m_Player_EnableRightRayInteractor;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @EnableLeftRayInteractor => m_Wrapper.m_Player_EnableLeftRayInteractor;
        public InputAction @EnableRightRayInteractor => m_Wrapper.m_Player_EnableRightRayInteractor;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @EnableLeftRayInteractor.started += instance.OnEnableLeftRayInteractor;
            @EnableLeftRayInteractor.performed += instance.OnEnableLeftRayInteractor;
            @EnableLeftRayInteractor.canceled += instance.OnEnableLeftRayInteractor;
            @EnableRightRayInteractor.started += instance.OnEnableRightRayInteractor;
            @EnableRightRayInteractor.performed += instance.OnEnableRightRayInteractor;
            @EnableRightRayInteractor.canceled += instance.OnEnableRightRayInteractor;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @EnableLeftRayInteractor.started -= instance.OnEnableLeftRayInteractor;
            @EnableLeftRayInteractor.performed -= instance.OnEnableLeftRayInteractor;
            @EnableLeftRayInteractor.canceled -= instance.OnEnableLeftRayInteractor;
            @EnableRightRayInteractor.started -= instance.OnEnableRightRayInteractor;
            @EnableRightRayInteractor.performed -= instance.OnEnableRightRayInteractor;
            @EnableRightRayInteractor.canceled -= instance.OnEnableRightRayInteractor;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnEnableLeftRayInteractor(InputAction.CallbackContext context);
        void OnEnableRightRayInteractor(InputAction.CallbackContext context);
    }
}
